### ISSUE TITLE
useCleanCache has some unexpected side effects

### ISSUE THREAD

**Issue by hans-d** [mfncooper/mockery#17]
using Yadda together mockery has some unexpected side effects.

```
# goes wrong
Yadda = require 'yadda'
mockery.enable useCleanCache: true

# works ok
mockery.enable useCleanCache: true
Yadda = require 'yadda'
```

Yadda behaves differently, see also https://github.com/acuminous/yadda/issues/34
There is no difference if modules are actually mocked or not.

**Comment by davglass** [comment]
This is the expected behavior, when you enable `mockery` it will start mocking new requires after that point. If you require before you enable `mockery` it can't do it's job.
