### ISSUE TITLE
Mockery doesn't seem to be doing anything

### ISSUE THREAD

**Issue by carn1x** [mfncooper/mockery#19]
views.js

```
controllers = require '../../modules/fixture/controllers.js'
exports.custom = (db) ->
  (req, res) ->
    controllers.custom req.body
      , (result) ->
        res.json result : result
      , (error) ->
        res.json 400, error : error
```

test.js

```
mockery = require "mockery"

exports.tests = (app, db, config) ->
  describe '#routes', ->
    describe '/fixture/custom', ->
      it 'should return status 400 if no request body was provided', (done) ->
        request app
          .post '/fixture/custom'
          .send
            body :
              players : []
          .expect 400, done

  describe '#views', ->
    describe '#custom', ->
      controller =
        custom : (body, success_callback, error_callback) ->
          console.log "###MOCK CONTROLLER BODY: #{req}"
          if body
            success_callback 'result'
          else
            error_callback 'error'
      mockery.enable()
      mockery.registerAllowable '../../modules/fixture/controllers.js', true
      mockery.registerMock '../../modules/fixture/controllers.js', controller

      it 'should return json keyed by result on success callback', (done) ->
        req =
          body : true
        res.json = (response) ->
          response.result.should.eql 'result'
          done()
        custom req, res
```

I get the error `TypeError: Cannot read property 'should' of undefined` which I have confirmed is due to my mock not getting registered as I'd like.

I'm thinking the problem is that `require(../../modules/fixture/controllers.js)` is happening before `test.tests(app, db, config)` is called, and so the require cache is already created.

Shouldn't `mockery.registerAllowable('../../modules/fixture/controllers.js', true)` allow me to override already required modules? I require quite a lot of switching between real and mock modules throughout many tests, so I'd prefer to be able to register mocks "just in time" rather than all at the beginning, for instance before instantiating my express app. Is this possible?

**Comment by BillBrower** [comment]
@carn1x Did you ever figure out whether or not "just in time mocking" is possible?

**Comment by carn1x** [comment]
Sorry @BillBrower, I did crack this, and I'm pretty sure I did it with mockery, but unfortunately I've long since stopped using Node and no longer have access to the source code of the related project so apologies I can't give any useful advise now :(
