### ISSUE TITLE
Mockery.resetCache() doesn't work where Mockery.deregisterMock() does

### ISSUE THREAD

**Issue by carn1x** [mfncooper/mockery#20]
tests.js

    mockery = require "mockery"
    mockery.enable
      warnOnUnregistered : false
      warnOnReplace : true
      useCleanCache : true

Later on I mock `controllers.js` and this works fine, with the test outputting `MOCK CONTROLLER` as expected.

      describe '#views', ->
        describe '#custom', ->
          controller =
            custom : (body, success_callback, error_callback) ->
              console.log 'MOCK CONTROLLER'
              if body
                success_callback 'result'
              else
                error_callback 'error'
          mockery.registerMock '../../modules/fixture/controllers.js', controller
          views = require '../../modules/fixture/views.js'
          custom = views.custom null

          it 'should return json keyed by result on success callback', (done) ->
            req =
              body : true
            res.json = (response) ->
              response.result.should.eql 'result'
              done()
            custom req, res

Then when I come to testing a different component, I want to run `mockery.resetCache()` before mocking other modules:

      describe '#controller', ->
        describe '#custom', ->
          body =
            players : []
          # Mock the launcher.
          launcher =
            launch : (players, map, player_spectate, success_callback, error_callback) ->
              if map? && map == 1
                success_callback 'success'
              else
                error_callback [
                  code : 1
                ]

          # THIS DOESN'T WORK:
          mockery.resetCache()
          # THIS WORKS:
          mockery.deregisterMock '../../modules/fixture/controllers.js'

          mockery.registerMock '../../modules/launcher/controllers.js', launcher
          custom = require '../../modules/fixture/controllers.js'
          .custom

          it 'should call the error callback if no players selected', (done) ->
            custom body
              , () ->
                return
              , (err) ->
                err.should.containEql '6 players'
                done()

If I rely on `mockery.resetCache()` I still end up with output of `MOCK CONTROLLER`. If I use `mockery.deregisterMock` however I get the desired effect.

**Comment by neverfox** [comment]
Is that expected behavior? All `resetCache` is supposed to do is ensure that the next call to `require` doesn't return a cached version. It's not supposed to stop any mocks that you have set up for that require call.

**Comment by gotwarlost** [comment]
+1 to the previous comment.
