### ISSUE TITLE
Error: Module did not self register

### ISSUE THREAD

**Issue by NerdPad** [mfncooper/mockery#45]
I get the following error, when mockery is enabled:

```
mockery.enable({
            warnOnReplace: false,
            warnOnUnregistered: false,
            useCleanCache: true
        });
```

```
[Error: Module did not self-register.]
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

My test cases work fine. How do I get rid of these errors?

**Comment by NerdPad** [comment]
@davglass I am using v1.6.2, and I am still getting the same error. Do I need to change anything in my code for this?

**Comment by NerdPad** [comment]
Respectful bump.

I am still getting the same errors console. I am using v1.6.2.

Is there a ways to just suppress these? If there is no way to fix them?

**Comment by davglass** [comment]
What version of Node are you using? Those error strings are from Node and not from Mockery AFAIK.

**Comment by NerdPad** [comment]
I m using v5.6.0

**Comment by davglass** [comment]
Thanks, I'll see if I can replicate this. I've seen this error in node 4.x+ but I'm unsure where it's coming from and how to fix it.

**Comment by NerdPad** [comment]
It only comes when I have useCleanCache: true

**Comment by davglass** [comment]
@NerdPad Just pushed up `mockery@1.7.0` which should fix your issue. Let me know if it doesn't.

**Comment by NerdPad** [comment]
Will verify. Thanks for the quick response.

**Comment by NerdPad** [comment]
@davglass I can confirm that this update did fix the issue. Thank you.

**Comment by davglass** [comment]
Awesome, thanks goes to @bengl for the fix 🍻

**Comment by rupamroy** [comment]
I am again getting the same error 

mockery version 1.7.0 , 2.0.0
node version 6.1.0
