### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by malhar-trivedi** [mfncooper/mockery#54]
Please release a version of this tool, so I can tag version in package.json.

**Comment by davglass** [comment]
Not sure what you expect me to do. Version `1.7.0` is published here:
http://registry.npmjs.org/mockery/latest

That's the latest change besides a badge change in the README which didn't need a release.

**Comment by malhar-trivedi** [comment]
interesting. I couldn't find landing page for mockery on npm website and I didn't see any release version in github project so I thought there were no version released for this project.
I'll use version `1.7.0` then.

**Comment by davglass** [comment]
Interesting, seems to be there now: https://www.npmjs.com/package/mockery

I know the npm site was breaking earlier, that may have been it.
