### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [mfncooper/mockery#72]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by ummahusla** [comment]
> Commits on Jun 26, 2017

As per latest commit which was 1,5 year I have a feeling that it's dead.

**Comment by ErnestoIslas** [comment]
Looks like it is not compatible with new Nodejs version. I am trying to mock `@cloudant/cloudant` in Nodejs 12.x and it is not working. Maybe, module loader has changed its implementation: `require('module')._load` is not more. 😞
